In [ ]:
import numpy as np

arr = np.array([1,2,3,4])
print(type(arr))

<class 'numpy.ndarray'>


In [ ]:
# 0으로 초기화된 배열
arr=np.zeros((3,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
# 빈 값으로 만들어진 배열
arr = np.empty((4,4))
print(arr)

[[1.70459446e-316 0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]]


In [ ]:
# 1로 가득찬 배열 만들기
arr = np.ones((3,3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# 배열의 생성
arr = np.arange(10) # 10개짜리 배열 만들어줘
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# ndarray 배열의 모양, 차원수, 데이터 타입 확인하기
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
arr.shape # 배열 모양 확인

(2, 3)

In [ ]:
arr.ndim # 차원수 확인

2

In [ ]:
arr.dtype # 데이터 타입 확인

dtype('int64')

In [ ]:
arr_float = arr.astype(np.float64)
arr_float.dtype

dtype('float64')

In [ ]:
arr_str = np.array(['1','2','3'])
arr_str.dtype

dtype('<U1')

In [ ]:
arr_int = arr_str.astype(np.int64)
arr_int.dtype

dtype('int64')

In [ ]:
# ndarray 배열의 연산
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])

In [ ]:
arr1 + arr2

array([[ 6,  8],
       [10, 12]])

In [ ]:
np.add(arr1,arr2)

array([[ 6,  8],
       [10, 12]])

In [ ]:
arr1 * arr2

array([[ 5, 12],
       [21, 32]])

In [ ]:
np.multiply(arr1,arr2)

array([[ 5, 12],
       [21, 32]])

In [ ]:
# ndarray 배열 슬라이싱 하기
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
arr_1 = arr[:2,1:3]
print(arr_1)

# :2는 0,1만 갖고 올 것임. 2는 탈락
# 1:3은 1부터 시작해서 3까지(0과 3이 날라감)

[[2 3]
 [5 6]]


In [ ]:
arr[0,2]

3

In [ ]:
arr[[0,1,2],[2,0,1]]

array([3, 4, 8])

In [ ]:
idx = arr > 3
print(idx)

[[False False False]
 [ True  True  True]
 [ True  True  True]]


In [ ]:
print(arr[idx]) # arr안에 idx값 True인 것만 출력됨

[4 5 6 7 8 9]


In [ ]:
redwine = np.loadtxt(fname='winequality-red.csv',delimiter=';',skiprows=1) # delimiter는 csv 파일 내 데이터 구별자 / 첫 줄은 데이터 아니니까 생략
print(redwine)

[[ 7.4    0.7    0.    ...  0.56   9.4    5.   ]
 [ 7.8    0.88   0.    ...  0.68   9.8    5.   ]
 [ 7.8    0.76   0.04  ...  0.65   9.8    5.   ]
 ...
 [ 6.3    0.51   0.13  ...  0.75  11.     6.   ]
 [ 5.9    0.645  0.12  ...  0.71  10.2    5.   ]
 [ 6.     0.31   0.47  ...  0.66  11.     6.   ]]


In [ ]:
# 합계
print(redwine.sum())

152084.78194


In [ ]:
# 평균
print(redwine.mean())

7.926036165311652


In [ ]:
# 축(axis)
print(redwine.sum(axis=0))
print(redwine.mean(axis=0))

[13303.1       843.985     433.29     4059.55      139.859   25384.
 74302.       1593.79794  5294.47     1052.38    16666.35     9012.     ]
[ 8.31963727  0.52782051  0.27097561  2.5388055   0.08746654 15.87492183
 46.46779237  0.99674668  3.3111132   0.65814884 10.42298311  5.63602251]


In [ ]:
redwine[:,0]#.mean()    # 앞 뒤가 비어있는 [:]은 전체 데이터를 의미함. 두 번재로 찍힌 ,0은 전체 데이터 중 제일 첫 번째 column을 의미함.

array([7.4, 7.8, 7.8, ..., 6.3, 5.9, 6. ])

In [ ]:
redwine.max(axis=0) # 축을 기준으로 각각 가장 큰 수

array([ 15.9    ,   1.58   ,   1.     ,  15.5    ,   0.611  ,  72.     ,
       289.     ,   1.00369,   4.01   ,   2.     ,  14.9    ,   8.     ])

In [ ]:
redwine.min(axis=0) # 축을 기준으로 각각 가장 작은 수

array([4.6    , 0.12   , 0.     , 0.9    , 0.012  , 1.     , 6.     ,
       0.99007, 2.74   , 0.33   , 8.4    , 3.     ])